<?php
$myaddons = array();
$maNum = 0;
$myaddons[$maNum] = array('193', '/uploads/allimg/160903/1-160Z3223603336.jpg');
$maNum = 1;
$myaddons[$maNum] = array('194', '/uploads/allimg/160903/1-160Z3230111R0.jpg');
$maNum = 2;
$myaddons[$maNum] = array('195', '/uploads/allimg/160903/1-160Z323062N53.jpg');
$maNum = 3;
$myaddons[$maNum] = array('196', '/uploads/allimg/160904/1-160Z4013135958.jpg');
$maNum = 4;
$myaddons[$maNum] = array('197', '/uploads/allimg/160904/1-160Z401320R56.jpg');
$maNum = 5;
