<?php
$myaddons = array();
$maNum = 0;
$myaddons[$maNum] = array('47', '/uploads/allimg/160829/1-160R9200233P6.jpg');
$maNum = 1;
$myaddons[$maNum] = array('48', '/uploads/allimg/160829/1-160R92026464Z.jpg');
$maNum = 2;
$myaddons[$maNum] = array('49', '/uploads/allimg/160829/1-160R9202TGT.jpg');
$maNum = 3;
$myaddons[$maNum] = array('50', '/uploads/allimg/160829/1-160R920304a41.jpg');
$maNum = 4;
$myaddons[$maNum] = array('51', '/uploads/allimg/160829/1-160R9203245M6.jpg');
$maNum = 5;
$myaddons[$maNum] = array('52', '/uploads/allimg/160829/1-160R9203I6132.jpg');
$maNum = 6;
