<li id="menu-item-269" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children submenu"><a href="http://worldcapitalimmi.cn/%e7%82%ba%e4%bb%80%e9%ba%bc%e9%81%b7%e7%a7%bb/"><span>意国风情</span></a>
<ul class="sub-menu">
	<li id="menu-item-409" class="menu-item menu-item-type-custom menu-item-object-custom"><a href="http://worldcapitalimmi.cn/#one"><span>意大利的饮食文化</span></a></li>
	<li id="menu-item-410" class="menu-item menu-item-type-custom menu-item-object-custom"><a href="http://worldcapitalimmi.cn/#two"><span>医疗卫生服务体系</span></a></li>
	<li id="menu-item-411" class="menu-item menu-item-type-custom menu-item-object-custom"><a href="http://worldcapitalimmi.cn/#three"><span>意大利的气候</span></a></li>
	<li id="menu-item-412" class="menu-item menu-item-type-custom menu-item-object-custom"><a href="http://worldcapitalimmi.cn/#four"><span>意大利的教育与学校</span></a></li>
	<li id="menu-item-413" class="menu-item menu-item-type-custom menu-item-object-custom"><a href="http://worldcapitalimmi.cn/#five"><span>意大利的艺术与历史</span></a></li>
	<li id="menu-item-414" class="menu-item menu-item-type-custom menu-item-object-custom"><a href="http://worldcapitalimmi.cn/#six"><span>意大利的传统与民俗</span></a></li>
	<li id="menu-item-415" class="menu-item menu-item-type-custom menu-item-object-custom"><a href="http://worldcapitalimmi.cn/#seven"><span>意大利的时尚</span></a></li>
	<li id="menu-item-416" class="menu-item menu-item-type-custom menu-item-object-custom"><a href="http://worldcapitalimmi.cn/#eight"><span>意大利的山川湖泊</span></a></li>
	<li id="menu-item-417" class="menu-item menu-item-type-custom menu-item-object-custom last-item"><a href="http://worldcapitalimmi.cn/#nine"><span>崇尚体育的民族</span></a></li>
</ul>
<span class="menu-toggle"></span></li>