<tr>
			<td style="float: left;background: none;">
				<a href="[field:arcurl/]" style="margin: 0px; padding: 0px; border: 0px; font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; text-decoration: none; outline: 0px; color: rgb(222, 0, 13);"><font color="#333333">[field:title/]</font></a></td>
			<td style="float: right;background: none;">
				<span style="color:#333333; font-family: Roboto, Arial, Tahoma, sans-serif; line-height: 12.1000003814697px;">[field:pubdate function="GetDateMK(@me)"/]</span></td>
		</tr>