<?php
$z[0]=Array("field","",49,77);
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",88,117);
$z[1][4]['name']="typename";
$z[2]=Array("channel","\r\n                    <li class=\"\">\r\n                      <a href=\"[field:typelink/]\" class=\"\">[field:typename function=\"cn_substr(@me,9)\"/]</a>\r\n                    </li>\r\n                  ",209,450);
$z[2][4]['type']="son";
$z[2][4]['noself']="yes";

?>