<div class="section_wrapper clearfix"><div class="items_group clearfix"><div class="column one-fifth column_column "><div class="column_attr"  style=""><div class="img-btn" style="padding:3px !important;background-color:#ffffff;">
<a href="http://worldcapitalimmi.cn/%E7%A0%81-papini/"><img src="[field:picname/]"></a>
</div></div></div><div class="column one-fourth column_column "><div class="column_attr"  style=""><div style="padding:10px !important;background-color:#ffffff;">
<a href="http://worldcapitalimmi.cn/%E7%A0%81-papini/"><span style="color:#ff0000;">[field:didian/] </span></a>
</div></div></div><div class="column one-third column_column "><div class="column_attr"  style=""><div style="padding:10px !important;background-color:#ffffff;">
<a href="http://worldcapitalimmi.cn/%E7%A0%81-papini/">[field:huxing/]</a>
</div>
</div></div><div class="column one-fifth column_column "><div class="column_attr"  style=""><div style="padding:10px !important;background-color:#ffffff;">
<a href="http://worldcapitalimmi.cn/%E7%A0%81-papini/">[field:price/]</a>
</div>
</div></div></div></div></div>

<div class="section   chiusura "  style="padding-top:10px; padding-bottom:20px; background-color:" ><div class="section_wrapper clearfix"><div class="items_group clearfix"></div></div></div>