<li id="menu-item-269" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children submenu"><a href="http://worldcapitalimmi.cn/%e7%82%ba%e4%bb%80%e9%ba%bc%e9%81%b7%e7%a7%bb/"><span>意国风情</span></a>
<ul class="sub-menu">
	{dede:channel type=son noself=yes}
	<li id="menu-item-409" class="menu-item menu-item-type-custom menu-item-object-custom"><a href="http://worldcapitalimmi.cn/#one"><span>意大利的饮食文化</span></a></li>
{/dede:channel}
</ul>
<span class="menu-toggle"></span></li>