<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="2";
$z[0][4]['col']="5";
$z[0][4]['value']="3";
$z[1]=Array("img"," /uploads/allimg/160722/1-160H2111Z7.jpg ",93,239);
$z[1][4]['ddimg']="/uploads/allimg/160722/1-160H2111Z7-lp.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="600";
$z[1][4]['height']="397";
$z[2]=Array("img"," /uploads/allimg/160722/1-160H2111950.jpg ",241,389);
$z[2][4]['ddimg']="/uploads/allimg/160722/1-160H2111950-lp.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="600";
$z[2][4]['height']="397";

?>