<?php
$z[0]=Array("field","",9,37);
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",108,137);
$z[1][4]['name']="typename";
$z[2]=Array("channel","\r\n                      <a href=\"[field:typelink/]\" class=\"\">\r\n                        <li class=\"\">\r\n                          [field:typename/]\r\n                        </li>\r\n                      </a>\r\n                    ",229,504);
$z[2][4]['type']="son";
$z[2][4]['noself']="yes";

?>