<?php
$z[0]=Array("field","",23,49);
$z[0][4]['name']="currentstyle";
$z[1]=Array("field","",59,87);
$z[1][4]['name']="typeurl";
$z[2]=Array("field","",95,124);
$z[2][4]['name']="typename";
$z[3]=Array("channel","\r\n	<li id=\"menu-item-409\" class=\"menu-item menu-item-type-custom menu-item-object-custom\"><a href=\"[field:typelink/]\"><span>[field:typename/]</span></a></li>\r\n",161,369);
$z[3][4]['type']="son";
$z[3][4]['noself']="yes";

?>