<?php
$z[0]=Array("arclist","\r\n<a id=\"logo\" href=\"/\"><img class=\"logo-main   scale-with-grid\" src=\"[field:litpic/]\"><img class=\"logo-sticky scale-with-grid\" src=\"[field:litpic/]\"><img class=\"logo-mobile scale-with-grid\" src=\"[field:litpic/]\" ></a>	\r\n",440,717);
$z[0][4]['row']="1";
$z[0][4]['orderby']="id";
$z[0][4]['typeid']="37";
$z[1]=Array("global","",787,806);
$z[1][4]['name']="qgrx";
$z[2]=Array("field","(@me==\"\")? @me=\" class='current_page_item' \":@me=\"\";",1109,1211);
$z[2][4]['name']="typeid";
$z[2][4]['runphp']="yes";
$z[3]=Array("global","",1221,1248);
$z[3][4]['name']="cfg_indexurl";
$z[4]=Array("channelartlist"," \r\n<li id=\"menu-item-269\" {dede:field.currentstyle/}><a href=\"{dede:field name='typeurl'/}\"><span>{dede:field name='typename'/}</span></a>\r\n<ul class=\"sub-menu\">\r\n	{dede:channel type=son noself=yes}\r\n	<li id=\"menu-item-409\" class=\"menu-item menu-item-type-custom menu-item-object-custom\"><a href=\"[field:typelink/]\"><span>[field:typename/]</span></a></li>\r\n{/dede:channel}\r\n</ul>\r\n<span class=\"menu-toggle\"></span></li>\r\n",1284,1763);
$z[4][4]['typeid']="1,2,3,4";
$z[5]=Array("channelartlist","\r\n<li id=\"menu-item-161\" {dede:field.currentstyle/}><a href=\"{dede:field name='typeurl'/}\"><span>{dede:field name='typename'/}</span></a></li>\r\n",1769,1977);
$z[5][4]['typeid']="5,6,7,8,9,10";
$z[6]=Array("global","",2106,2138);
$z[6][4]['name']="cfg_templets_skin";

?>