<?php
$z[0]=Array("global","",388,415);
$z[0][4]['name']="cfg_indexurl";
$z[1]=Array("global","",508,540);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",665,697);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",786,818);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("field","(@me==\"\")? @me=\" class='current_page_item' \":@me=\"\";",1242,1344);
$z[4][4]['name']="typeid";
$z[4][4]['runphp']="yes";
$z[5]=Array("global","",1354,1381);
$z[5][4]['name']="cfg_indexurl";
$z[6]=Array("channelartlist"," \r\n<li id=\"menu-item-269\" {dede:field.currentstyle/}><a href=\"{dede:field name='typeurl'/}\"><span>{dede:field name='typename'/}</span></a>\r\n<ul class=\"sub-menu\">\r\n	{dede:channel type=son noself=yes}\r\n	<li id=\"menu-item-409\" class=\"menu-item menu-item-type-custom menu-item-object-custom\"><a href=\"[field:typelink/]\"><span>[field:typename/]</span></a></li>\r\n{/dede:channel}\r\n</ul>\r\n<span class=\"menu-toggle\"></span></li>\r\n",1417,1896);
$z[6][4]['typeid']="1,2,3,4";
$z[7]=Array("channelartlist","\r\n<li id=\"menu-item-161\" {dede:field.currentstyle/}><a href=\"{dede:field name='typeurl'/}\"><span>{dede:field name='typename'/}</span></a></li>\r\n",1902,2110);
$z[7][4]['typeid']="5,6,7,8,9,10";
$z[8]=Array("global","",2239,2271);
$z[8][4]['name']="cfg_templets_skin";

?>