<?php
$z[0]=Array("field","",743,770);
$z[0][4]['name']="weburl";
$z[1]=Array("type","\r\n              <li class=\"\">\r\n                <a href=\"[field:typeurl/]\" class=\"\">[field:typename/]</a>\r\n              </li>\r\n            ",810,981);
$z[1][4]['typeid']="1";
$z[2]=Array("channelartlist","\r\n              <li class=\"am-parent\">\r\n                <a href=\"{dede:field name='typeurl'/}\" class=\"\">{dede:field name='typename'/}</a>\r\n                <ul class=\"am-menu-sub am-collapse  am-avg-sm-3 \">\r\n                  {dede:channel type=son noself=yes}\r\n                    <li class=\"\">\r\n                      <a href=\"[field:typelink/]\" class=\"\">[field:typename function=\"cn_substr(@me,9)\"/]</a>\r\n                    </li>\r\n                  {/dede:channel}\r\n                </ul>\r\n              </li>\r\n            ",995,1575);
$z[2][4]['typeid']="2,3,4";
$z[3]=Array("channelartlist","\r\n              <li class=\"\">\r\n                <a href=\"{dede:field name='typeurl'/}\" class=\"\">{dede:field name='typename'/}</a>\r\n              </li>\r\n            ",1589,1816);
$z[3][4]['typeid']="5,6,7,8,9,10";

?>