<?php
$z[0]=Array("global","",297,323);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("include","",1979,2014);
$z[1][4]['filename']="head.htm";
$z[2]=Array("arclist","\r\n        <li>\r\n          <img src=\"[field:picname/]\">\r\n        </li>\r\n      ",2184,2300);
$z[2][4]['typeid']="29";
$z[3]=Array("type","\r\n          <a href=\"[field:typelink/]#3\" class=\"\">\r\n        ",2608,2701);
$z[3][4]['typeid']="6";
$z[4]=Array("type","\r\n          <a href=\"[field:typelink/]#2\" class=\"\">\r\n        ",2878,2971);
$z[4][4]['typeid']="6";
$z[5]=Array("type","\r\n          <a href=\"[field:typelink/]#4\" class=\"\">\r\n        ",3145,3238);
$z[5][4]['typeid']="6";
$z[6]=Array("type","\r\n          <a href=\"[field:typelink/]#1\" class=\"\">\r\n        ",3415,3508);
$z[6][4]['typeid']="6";
$z[7]=Array("type","\r\n          <a href=\"[field:typelink/]\" class=\"\">\r\n        ",3685,3776);
$z[7][4]['typeid']="1";
$z[8]=Array("type","\r\n          <a href=\"[field:typelink/]\" class=\"\">\r\n        ",3959,4050);
$z[8][4]['typeid']="7";
$z[9]=Array("type","\r\n          <a href=\"[field:typelink/]\" class=\"\">\r\n        ",4230,4321);
$z[9][4]['typeid']="8";
$z[10]=Array("type","\r\n          <a href=\"[field:typelink/]\" class=\"\">\r\n        ",4493,4584);
$z[10][4]['typeid']="3";
$z[11]=Array("type","\r\n          <a href=\"[field:typelink/]\" class=\"\">\r\n        ",6582,6674);
$z[11][4]['typeid']="41";
$z[12]=Array("type","\r\n          <a href=\"[field:typelink/]\" class=\"\">\r\n        ",6838,6930);
$z[12][4]['typeid']="42";
$z[13]=Array("type","\r\n          <a href=\"[field:typelink/]\" class=\"\">\r\n        ",7094,7186);
$z[13][4]['typeid']="27";
$z[14]=Array("type","\r\n          <a href=\"[field:typelink/]\" class=\"\">\r\n        ",7350,7442);
$z[14][4]['typeid']="28";
$z[15]=Array("arclist","\r\n        <li class=\"am-g am-list-item-dated\">\r\n          <a href=\"[field:arcurl/]\" class=\"am-list-item-hd \" target=\"_blank\">[field:fulltitle/]</a>\r\n          <span class=\"am-list-date\">[field:pubdate function=\"GetDateMK(@me)\"/] </span>\r\n        </li>\r\n      ",10363,10672);
$z[15][4]['row']="100000";
$z[15][4]['typeid']="30";
$z[16]=Array("arclist","\r\n          <li><a href=\"[field:arcurl/]\" target=\"_blank\"><font>[field:fulltitle/]</font><span>[field:pubdate function=\"GetDateMK(@me)\"/]</span></a></li>\r\n        ",11035,11248);
$z[16][4]['row']="100000";
$z[16][4]['typeid']="30";

?>