<?php
$z[0]=Array("field","",290,309);
$z[0][4]['name']="title";
$z[1]=Array("global","",310,336);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1958,1993);
$z[2][4]['filename']="head.htm";
$z[3]=Array("list","\r\n        <li class=\"am-g am-list-item-dated\">\r\n          <a href=\"[field:arcurl/]\" class=\"am-list-item-hd \">[field:title/]</a>\r\n          <span class=\"am-list-date\">[field:pubdate function=\"GetDateMK(@me)\"/]</span>\r\n        </li>\r\n        ",2178,2479);
$z[3][4]['pagesize']="12";
$z[3][4]['orderby']="id";
$z[3][4]['titlelen']="100";
$z[4]=Array("pagelist","",2528,2606);
$z[4][4]['listitem']="info,index,end,pre,next,pageno,option";
$z[4][4]['listsize']="5";
$z[5]=Array("include","",2647,2684);
$z[5][4]['filename']="footer.htm";

?>